### ISSUE TITLE
Robotlegs-pixi MediatorFactory does not work after latest changes from RobotlegsJS

### ISSUE THREAD

**Issue by D4rkL1ch** [GoodgameStudios/RobotlegsJS-Pixi#34]
Hey,
we are using RobotlegsJS with Robotlegs-Pixi. 
I have seen that 22 hours ago this commit (https://github.com/GoodgameStudios/RobotlegsJS/commit/192c10882ac9fb0372de34d74e2b9e52339e7b69#diff-8b7f7f2a1ef709261d62e5ca868bbf6b) changed IInjector interface.
This rendered Robotlegs-Pixi crashing when mapping mediators to views.
Are you planning to support Robotlegs-Pixi still?

**Comment by tiagoschenkel** [comment]
Hi @D4rkL1ch!

Yes, we are aware of this, the **RobotlegsJS** framework is now using latest version of **InversifyJS**, and we had to introduce breaking changes due to this fact.

I'm planning to update the **Robotlegs-Pixi** framework soon, probably it will be done by the end of this week.

**Comment by D4rkL1ch** [comment]
Thanks a lot for the fast response!

**Comment by pasviegas** [comment]
Yeah, same here! Thanks :D
