### ISSUE TITLE
Generic support

### ISSUE THREAD

**Issue by cuongdd2** [GoodgameStudios/RobotlegsJS-Pixi#4]
In a Haxe port of Robotlegs ([MMVC](https://github.com/massiveinteractive/mmvc)) they support generic.
For example:

```
class TestMediator extends Mediator<TestView> {
}
```

so you don't need duplicate view class injection for every Mediator class.
Actionscript does not support generic but Typescript does. Do you guys think it is a good choice. If yes, I will make a PR soon :).

Thanks.

**Comment by endel** [comment]
Hi @cuongdd2, that would be great indeed! The only concern is that the framework expects an `IEventDispatcher` as a view component. Maybe we could use the generic and just cast it to `IEventDispatcher` when needed.
